grpc:
  server:
    port: 9000

spring:
  application:
    name: "cart-service"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: org.hibernate.dialect.MySQL5Dialect
    url: jdbc:mysql://localhost/productivity
    username: root
    password: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
server:
  port: 8082
