spring:
  application:
    name: "product-service"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: org.hibernate.dialect.MySQL5Dialect
    url: jdbc:mysql://mysql_database/productivity
    username: mysql
    password: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
server:
  port: 8084
  context-path: /product-service