grpc:
  client:
    grpc-cart-service:
      address: static://localhost:9000
      negotiationType: plaintext

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: 8081